version: '3.9'

services:
  db:
    image: postgres:16.3
    container_name: postgres-bd
    environment:
      POSTGRES_PASSWORD: postgres!
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - /home/romulo/docker-volumes/postgres-bd/db:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    volumes:
      - /home/romulo/docker-volumes/pgadmin:/var/lib/pgadmin/backups
    depends_on:
      - db
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
